app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_user:
    resource: "@AppBundle/Resources/config/routing.security.yml"
    prefix:     /


dashboard:
    resource: "@AppBundle/Resources/config/routing.dashboard.yml"
    prefix: /app/

user:
    resource: "@AppBundle/Resources/config/routing.user.yml"
    prefix: /app/

client:
    resource: "@AppBundle/Resources/config/routing.client.yml"
    prefix: /app/