jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    # after authentication, the session will be migrated
    session_fixation_strategy: migrate

    access_denied_url:    ~ # Example: /foo/error403
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       SUPER_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        custom_members:
           entity: { class: AppBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/api/(_(profiler|wdt|doc|member/create))/
            security: false

        main:
            pattern: /.*
            form_login:
                check_path: _security_check
                login_path: /login.html
                target_path_parameter: redirect_url
                default_target_path: /secured/dashboard.html
                # by default, the login form *must* be a POST, not a GET
                post_only:      true
                remember_me:    true
            logout:
                path:   /logout.html
                target: /login.html
                invalidate_session: true
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }
            security: true
            anonymous: true            #anonymous: ~
            switch_user: true
            remember_me:
                key:      "%secret%"
                lifetime: 86400 # 1 day in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER


    access_control:
        - { path: ^/login.html, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/secured/*, roles: [IS_AUTHENTICATED_FULLY,IS_AUTHENTICATED_REMEMBERED], requires_channel: http }
