<?php

namespace AppBundle\Entity\Repository;

/**
 * PartyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
