<?php

namespace AppBundle\Entity\Repository;

/**
 * PartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyRepository extends \Doctrine\ORM\EntityRepository
{
}
