<?php

namespace AppBundle\Entity\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get status
     *
     * @param string $status
     * @return AppBundle:Status
     */
    public function getStatus($status)
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.name = :status_name')
            ->setParameter('status_name', $status);

        return $qb->getQuery()->getSingleResult();
    }
}
